apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
  ports:
    - port: 27017
      targetPort: 27017